server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/presensi-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: INFO

app:
  jwt:
    secret: "change-this-dev-secret-please-32-bytes-minimum-key"
    expirationMillis: 2592000000 # 30 days
  uploadDir: ./uploads

# enable swagger-ui at /swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
